version: "3"

services:
  recommendation:
    build:
      context: ./recommendation
    ports:
      - "8080:8080"
    environment:
      ACCESS_TOKEN: secret
      PORT: 8080
  temperature:
    build:
      context: ./temperature
    ports:
      - "8081:8081"
    environment:
      ACCESS_TOKEN: secret
      PORT: 8081
  light_luminosity:
    build:
      context: ./luminosity_humidity
    ports:
      - "8082:8082"
    environment:
      ACCESS_TOKEN: secret
      PORT: 8082
